# Generated by Django 3.1.1 on 2021-03-17 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0002_auto_20210317_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(blank=True, max_length=255, null=True)),
                ('article_url', models.URLField()),
                ('download_latency', models.FloatField()),
                ('http_error', models.IntegerField(default=0)),
                ('dns_error', models.IntegerField(default=0)),
                ('timeout_error', models.IntegerField(default=0)),
                ('base_error', models.IntegerField(default=0)),
                ('skip_url', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='base_error',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='dns_error',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='download_latency',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='http_error',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='skip_url',
        ),
        migrations.RemoveField(
            model_name='crawler',
            name='timeout_error',
        ),
        migrations.CreateModel(
            name='CrawlerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawlers', models.ManyToManyField(to='scraper.CrawlerItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
