# Generated by Django 3.1.1 on 2021-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_crawleritem_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleritem',
            name='article_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Error', 'Error'), ('Processing', 'Processing'), ('Queued', 'Queued')], max_length=100),
        ),
    ]
