# Generated by Django 3.1.1 on 2021-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20210320_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleritem',
            name='collection_name',
            field=models.CharField(choices=[('global_link', 'global_link'), ('article_link', 'article_link')], max_length=255),
        ),
    ]
