# Generated by Django 3.1.1 on 2021-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20210318_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespider',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
