# Generated by Django 3.1.1 on 2021-03-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_articlespider_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='json_log',
        ),
        migrations.AddField(
            model_name='scraper',
            name='crawler_set',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='scraper.crawlerset'),
            preserve_default=False,
        ),
    ]
