# Generated by Django 3.1.1 on 2021-03-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20210320_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='debug_log',
        ),
        migrations.AddField(
            model_name='scraper',
            name='time_finished',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
