# Generated by Django 3.1.1 on 2021-03-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20210318_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerset',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
