# Generated by Django 3.1.1 on 2021-03-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_crawlerset_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='collection_name',
            field=models.CharField(default='article_link', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawleritem',
            name='download_latency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
