# Generated by Django 3.1.1 on 2021-03-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20210321_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlethread',
            old_name='crawlers',
            new_name='articles',
        ),
    ]
