# Generated by Django 3.1.1 on 2021-03-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20210321_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlespider',
            old_name='is_finished',
            new_name='in_use',
        ),
        migrations.RenameField(
            model_name='articlethread',
            old_name='is_finished',
            new_name='in_use',
        ),
        migrations.AddField(
            model_name='article',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
