# Generated by Django 3.1.1 on 2021-03-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20210319_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='article_error_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawleritem',
            name='article_status',
            field=models.CharField(default='Done', max_length=100),
            preserve_default=False,
        ),
    ]
