# Generated by Django 3.1.1 on 2021-03-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20210321_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='crawler_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.crawlerset'),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='spiders',
            field=models.ManyToManyField(to='scraper.ArticleSpider'),
        ),
    ]
