# Generated by Django 3.1.1 on 2021-03-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20210321_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawleritem',
            name='collection_name',
        ),
    ]
