# Generated by Django 3.1.1 on 2021-03-23 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_remove_crawleritem_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='date_parsed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
