# Generated by Django 3.1.1 on 2021-03-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_crawleritem_date_parsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawleritem',
            name='date_parsed',
        ),
    ]
