# Generated by Django 3.1.1 on 2021-03-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_crawlerset_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='fqdn',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
