# Generated by Django 3.1.1 on 2021-03-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_crawleritem_fqdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='terminated_process',
            field=models.BooleanField(default=False),
        ),
    ]
