# Generated by Django 3.1.1 on 2021-03-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_scraper_terminated_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapers', models.ManyToManyField(to='scraper.Scraper')),
            ],
        ),
    ]
