# Generated by Django 3.1.1 on 2021-03-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_scraperanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraperanalysis',
            options={'verbose_name_plural': 'Scraper Analysis'},
        ),
    ]
