# Generated by Django 3.1.1 on 2021-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_auto_20210330_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='link_created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crawleritem',
            name='proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crawleritem',
            name='user_agent',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
