# Generated by Django 3.1.1 on 2021-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_auto_20210411_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='parser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
