# Generated by Django 3.1.1 on 2021-04-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0024_crawleritem_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='article_date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
