# Generated by Django 3.1.1 on 2021-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0026_crawleritem_handle_httpstatus_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='redirect_urls',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
