# Generated by Django 3.1.1 on 2021-05-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0028_crawleritem_redirect_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleritem',
            name='custom_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
