# Generated by Django 3.1.1 on 2021-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0031_auto_20210529_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerset',
            name='crawlers',
            field=models.ManyToManyField(to='scraper.CrawlerItem'),
        ),
    ]
